name: 08 - Using Variables

run-name:  08-variables | DEBUG - ${{ inputs.debug }}


on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
env:
 MY_WORKFLOW_VAR: "I am a workflow env var"
 MY_OVERWRITTEN_VAR: "I will be overwritten"
    
jobs:
 echo-data:
  runs-on: ubuntu-latest
  env:
    MY_WORKFLOW_VAR: "job"
    MY_OVERWRITTEN_VAR: "job"
  steps:
   - name: Display Info
     run: |
      echo "Event name ${{github.event_name}}"
      echo "Ref: ${{github.ref}}"
      echo "SHA: ${{github.sha}}"
      echo "Actor: ${{github.actor}}"
      echo "Workflow: ${{github.workflow}}"
      echo "Run Id: ${{github.run_id}}"
      echo "Run number: ${{github.run_number}}"
   - name: Retreieve Variables
     
     env:
        MY_WORKFLOW_VAR: "step"
        MY_OVERWRITTEN_VAR: "step"
     run:  |
      echo "Variables: ${{vars.MY_VAR}}"
      echo "Env variable is: ${{env.MY_WORKFLOW_VAR}}"
      echo  "ENV variable is: ${{env.MY_OVERWRITTEN_VAR}}"
      echo  "ENV variable is: $MY_WORKFLOW_VAR"
 echo-stag:
  runs-on: ubuntu-latest
  environment: staging
  steps: 
     - name: Print staging variable 
       run: |
         echo  "Environment variable is: ${{vars.TARGET_VAR }}"
